### ISSUE TITLE
subscriptionClient.subscribe is not a function (React + Relay)

### ISSUE THREAD

**Issue by tarikjn** [howtographql/howtographql#229]
`subscriptions-transport-ws` has removed the Subscription Manager (it was deprecated), see https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/CHANGELOG.md for 0.9.0

**Comment by nicerr** [comment]
I also had this problem but managed to get the subscription to work by using `subscriptions-transport-ws@0.6.0`

Would be nice to have the example demonstrate the code needed for the latest version of `subscriptions-transport-ws` though.

**Comment by nikolasburk** [comment]
Thanks for pointing this out @tarikjn, the tutorial has been updated accordingly with the info to install version `0.8.3` of the package which still exports the `SubscriptionClient`.

Unfortunately I don't have the time atm to update the tutorial to use the latest version, but would definitely welcome a PR if anyone finds the time 🙂

**Comment by Nieto2018** [comment]
Thank a lot @nikolasburk for your graphcool tutorial (https://www.howtographql.com/react-relay/0-introduction/), but ran the tutorial i got the mentioned error in the title topic with subscriptions and found a solution that works with subscriptions-transport-ws 0.9.15.

The solution thanks to @jeremy-colin:
https://github.com/jeremy-colin/relay-examples-subscription/blob/master/js/environment.js

Sorry my english.
